#!/usr/bin/env escript
%% -*- erlang -*-
%%! -name retina@127.0.0.1 -setcookie cookie

-import(hexagonal).

main(_Args) ->
	hexagonal:start(25),
	% 2 seconds to get info
	timer:sleep(1200), 
	{S,A} = hexagonal:info(),
	io:format("Size: predicted ~w, actual ~w~n", [S, A]),
	% 3 seconds to start visualizer
	timer:sleep(1800),
	hexagonal:morph(),
	loop().

loop() ->
	receive
		stop -> ok
	end.
